version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build-and-publish:
    executor: win/default
  
    steps:
      - checkout
      - run:
          name: Restore packages
          command: nuget restore GrasshopperAsyncComponent.sln
      - run:
          name: Build solution
          command: msbuild GrasshopperAsyncComponent.sln /p:Configuration=Release
      - run:
          name: Pack NuGet
          command: cd GrasshopperAsyncComponent; nuget pack GrasshopperAsyncComponent.csproj -Prop Configuration=Release
      - run:
          name: Pack NuGet
          command: nuget push ${NUGET_AUTH_TOKEN} -Source https://api.nuget.org/v3/index.json *.nupkg


workflows:
  publish:
    jobs:
      - build-and-publish:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/


    